tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: DATA_BUILD_TOOL
      schema: dev
      warehouse: SANDBOX_XS
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: DATA_BUILD_TOOL
      schema: prod
      warehouse: SANDBOX_XS